set(output_bin thread_lamda_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_lamda.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})

set(output_bin thread_non_static_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_non_static.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})

set(output_bin thread_static_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_static.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})

set(output_bin thread_mutex_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_mutex.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})

set(output_bin thread_multi_mutex_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_multi_mutex.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})

set(output_bin thread_trylock_test)
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_executable(${output_bin} thread_trylock.cpp)
set_target_properties(${output_bin} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(${output_bin})
